### ISSUE TITLE
Main CTA sub-title sample text with issues (fresh install)

### ISSUE THREAD

**Issue by IonRutz** [ColorlibHQ/pixova-lite#46] opened 2016-09-09 14:02 UTC
![image](https://cloud.githubusercontent.com/assets/15014267/18389559/264de5d4-76af-11e6-97a3-96a17ba285dc.png)

**Comment by cristianraiber** [comment] 2017-07-07 13:35
Duplicate of #60

**Closed as completed by cristianraiber** 2017-07-07 13:35 UTC
Labels: Bug, Need Testing
